### ISSUE TITLE
Compatibility with Rails 2.x

### ISSUE THREAD

**Issue by mjackson** [maccman/sprockets-commonjs#12]
It looks like you're no longer supporting Rails 2.x. For example, you're using Rails::Engine which, AFAIK, is a Rails 3 thing. Would you be opposed to adding back support for it?

**Comment by maccman** [comment]
Yes, I would be opposed. I'm sorry, but I'd rather not deal with older
versions of Rails.

On Thu, Sep 13, 2012 at 5:16 PM, Michael Jackson
notifications@github.comwrote:

> It looks like you're no longer supporting Rails 2.x. For example, you're
> using Rails::Engine which, AFAIK, is a Rails 3 thing. Would you be opposed
> to adding back support for it?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/maccman/sprockets-commonjs/issues/12.

## 

Alex MacCaw

+12147175129
@maccman

http://alexmaccaw.com

**Comment by mjackson** [comment]
You and me both. :)

**Comment by maccman** [comment]
Although the `edge` branch doesn't use Engines (but requires a up-to-date version of Sprockets)

**Comment by mjackson** [comment]
Right on. Thanks for the quick reply. I can totally understand your desire to look forward instead of back. I'll check out the edge version and see if I can make it work with our rails stack. Thanks!
