### ISSUE TITLE
Problem with Rails 4.0

### ISSUE THREAD

**Issue by mulderp** [maccman/sprockets-commonjs#22]
I am just trying out this gem with a fresh Rails 4.0 app, but I get:

<pre>
/Users/pmu/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/sprockets-commonjs-0.0.5/lib/sprockets/commonjs/engine.rb:7:in `<class:CommonJS>': uninitialized constant Sprockets::Rails::Engine (NameError)
    from /Users/pmu/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/sprockets-commonjs-0.0.5/lib/sprockets/commonjs/engine.rb:5:in `<module:Sprockets>'
    from /Users/pmu/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/sprockets-commonjs-0.0.5/lib/sprockets/commonjs/engine.rb:4:in `<top (required)>'
    from /Users/pmu/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/sprockets-commonjs-0.0.5/lib/sprockets/commonjs.rb:49:in `require'
    from /Users/pmu/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/sprockets-commonjs-0.0.5/lib/sprockets/commonjs.rb:49:in `<top (required)>'
    from /Users/pmu/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/sprockets-commonjs-0.0.5/lib/sprockets-commonjs.rb:1:in `require'
    from /Users/pmu/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/sprockets-commonjs-0.0.5/lib/sprockets-commonjs.rb:1:in `<top (required)>'
    from /Users/pmu/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
</pre>

Not sure what is going wrong here.

**Comment by mulderp** [comment]
this is fixed when using latest:

git://github.com/maccman/sprockets-commonjs.git

**Comment by vendethiel** [comment]
@maccman Hey ! Do you have any idea when you're gonna tag 0.7 on rubygems :) ?

**Comment by alecguintu** [comment]
@maccman Bump on when 0.7 would be on rubygems?

**Comment by andyl** [comment]
Still broken...

**Comment by ktusznio** [comment]
Bump.

**Comment by seekshiva** [comment]
Still broken..
