### ISSUE TITLE
JST templating shortcut

### ISSUE THREAD

**Issue by mulderp** [maccman/sprockets-commonjs#23]
I am note sure if this is an issue with CommonJS or Sprockets. I would like to use JST for a template within a widget module:

<pre>
var LoginView = Backbone.View.extend({

  template: JST["templates/login"],

  initialize: function() {
    console.log("join");
  }

});
</pre>

The JST is not found.

**Comment by mulderp** [comment]
I will try with:

<pre>
function(template, data) {
  return HandlebarsTemplates[template](data);
};
</pre>

**Comment by alduro** [comment]
Have you solved this ? I'm having the same issue. JST cannot be accessed from within Backbone.View.
