### ISSUE TITLE
Add strict pragma to wrapper

### ISSUE THREAD

**Issue by knuton** [maccman/sprockets-commonjs#28]
I see benefit in (optionally) adding a strict pragma (`"use strict";`) at the top of the wrapper function.

Sounds good? I'd volunteer.

**Comment by maccman** [comment]
I think this would make more sense in another preprecessor. Although, is this not possible to the wrapper func?

**Comment by knuton** [comment]
> Although, is this not possible to the wrapper func?

Sorry, I somehow fail to parse this sentence. ;)

I think you may be right, it's probably more flexible to solve this through another preprocessor, seeing that third-party modules may not comply.

**Comment by maccman** [comment]
Sorry, I meant: Although, is this not possible due to the wrapper func?

I think CoffeeScript has a use strict option. Not something you'd want to use in prod though.
